name: Student API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman API Tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          newman run "Student Practice API Collection.postman_collection.json" \
            --env-var "base_url=$BASE_URL" \
            --env-var "token=$API_TOKEN"